diploiTemplateVersion: V1.0
name: diploi-sveltekit
description: A starter template for SvelteKit
defaultName: SvelteKit ToDo

stages:
  - name: Development
    identifier: development
  - name: Staging
    identifier: staging
  - name: Production
    identifier: production

contexts:
  - name: app
    identifier: app
  - name: postgres
    identifier: postgres

parameterGroups:
  - name: PostgreSQL Database
    identifier: postgres
    toggleable: true
    description: Database connection info
    defaultValue: TRUE
    parameters:
      - name: Host
        identifier: POSTGRES_HOST
        defaultValue: postgres
        type: string
      - name: Port
        identifier: POSTGRES_PORT
        defaultValue: 5432
        type: integer
      - name: User
        identifier: POSTGRES_USER
        defaultValue: postgres
        type: string
        contexts: label=postgres,label=app
      - name: Password
        identifier: POSTGRES_PASSWORD
        defaultValue: postgres
        type: secret
      - name: Schema
        identifier: POSTGRES_DB
        defaultValue: todo
        type: string

environmentVariables:
  - identifier: VITE_PORT
    defaultValue: 5173
    type: number
    contexts: label=app

repositories:
  - name: app
    identifier: app
    initialProjectRepositoryUrl: github.com/diploi/sveltekit-template-demo

hosts:
  - name: App
    identifier: app
    urlFormat: '[name].[default-domain]'

editors:
  - name: App
    identifier: app
    service: app
    port: 3001
    stages:
      - development

ssh:
  - usernameFormat: 'app'
    contexts: label=app
    stages:
      - development
  - usernameFormat: 'app-[index]'
    contexts: label=app
    stages:
      - staging
      - production

logs:
  - identifier: vite-log
    name: Vite Log
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/www.log
    stages:
      - development
  - identifier: sveltekit-log
    name: SvelteKit Log
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/www.log
    stages:
      - staging
      - production

actions:
  - identifier: vite-restart
    name: Restart Vite
    labelSelector: app=app
    command: supervisord restart www
    stages:
      - development
  - identifier: sveltekit-restart
    name: Restart SvelteKit
    labelSelector: app=app
    command: supervisord restart www
    stages:
      - staging
      - production

images:
  - identifier: app
    repository: app
    dockerfile: Dockerfile
    image: ghcr.io/diploi/sveltekit-template
    initialProjectImage: ghcr.io/diploi/sveltekit-template-initial-project
    stages:
      - development
      - staging
      - production
    buildStages:
      - staging
      - production

storage:
  - identifier: app
    stages:
      - development
    sizeMb: 6144
  - identifier: postgres
    stages:
      - production
      - staging
      - development
    sizeMb: 4096

status:
  url: http://app:3000/status
