apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: 80
      targetPort: app-vite
      name: app
    - port: 3000
      targetPort: app-status
      name: status
  selector:
    app: {{ ternary "app" "disabled" .Values.enabled }}
