apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: 80
      targetPort: app-vite
      name: app
    - port: 3000
      targetPort: app-status
      name: status
    - port: 3001
      name: editor
      targetPort: app-editor
  selector:
    app: app
